services:
  insights:
    image: ghcr.io/navidrome/insights:main
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - PORT=8080
    volumes:
      - .:/app

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - insights
